openapi: 3.2.0
info:
  title: aox-django-backend Announcements API
  version: 1.0.0
tags:
- name: Announcements
paths:
  /announcements/:
    get:
      operationId: announcements_retrieve
      tags:
      - Announcements
      responses:
        '200':
          description: No response body
      summary: Announcements retrieve
      x-summary-source: derived
